spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: QIUHEchamygn1996@
    url: jdbc:mysql://localhost:3306/springSecurityDemo

  jpa:
    show-sql: true